### ISSUE TITLE
Track is not defined

### ISSUE THREAD

**Issue by mcvarer** [javiersanp/insta360pro-gps#3]
Hi Javier Sanchez Portero,

I trid to extraxt .gpx format from 
https://support.remotegeo.com/wp-content/uploads/wpforo/default_attachments/1564266519-VID_20190621_085118_00_0089.mp4

`    python insta360pro-gps.py insta360/one-X/1564266519-VID_20190621_085118_00_0089.mp4 result`

```
Bad input file 'utf-8' codec can't decode byte 0x94 in position 41: invalid start byte
Traceback (most recent call last):
File "insta360pro-gps.py", line 74, in <module>
togpx(track, fo)
NameError: name 'track' is not defined
```

Can you help me, please?

**Comment by javiersanp** [comment]
You should extract first the GPS info from the video to a txt file whit the
tool GPSreader.exe tool included in the Insta360 Stitcher software. Then
apply the script to the txt file instead of the MP4 file.
